// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/main/jflex/archivo.lex

package com.cunoc.practica1.backEnd.AFND;

import com.cunoc.practica1.backEnd.report.Errores;
import com.cunoc.practica1.frontEnd.accionesBotton.Conexion;
import com.cunoc.practica1.frontEnd.paneles.panelReporte.PanelReporte;

import java_cup.runtime.Symbol;



@SuppressWarnings("fallthrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\u10fe\u0200";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\12\0\1\1\2\0\1\1\22\0\1\2\7\0\1\3"+
    "\1\4\1\5\1\6\1\7\1\10\1\11\1\12\12\13"+
    "\7\0\1\14\1\15\1\16\1\17\1\20\1\21\1\22"+
    "\1\23\1\24\1\25\1\23\1\26\1\27\1\30\1\31"+
    "\1\32\1\23\1\33\1\34\1\35\1\36\1\37\3\23"+
    "\1\40\4\0\1\23\1\0\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\23\1\26"+
    "\1\27\1\30\1\31\1\32\1\23\1\33\1\34\1\35"+
    "\1\36\1\37\3\23\1\40\265\0\2\41\115\0\1\42"+
    "\u0180\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[768];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\13\14\1\0\7\14\1\0"+
    "\2\14\1\0\6\14\1\13\2\14\1\0\6\14\1\0"+
    "\2\14\1\0\1\14\1\0\6\14\1\0\3\14\1\0"+
    "\1\15\5\14\1\0\1\14\2\16\1\14\1\0\3\14"+
    "\1\0\1\14\1\17\2\20\2\14\1\0\1\14\1\0"+
    "\2\14\1\0\2\14\1\21\1\0\1\14\1\0\2\22"+
    "\3\14\1\0\1\14\1\23\1\14\1\0\2\24\1\25"+
    "\1\14\1\0\2\14\1\0\1\14\1\0\3\14\1\0"+
    "\2\14\1\0\2\26\1\27\1\14\1\27\1\14\1\0"+
    "\1\30\1\0\1\14\1\0\1\14\2\31\1\32\2\33"+
    "\1\0\2\34\1\14\1\0\1\14\1\0\1\35\4\0"+
    "\1\36";

  private static int [] zzUnpackAction() {
    int [] result = new int[159];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\43\0\43\0\43\0\43\0\43\0\43\0\43"+
    "\0\43\0\43\0\43\0\106\0\151\0\214\0\257\0\322"+
    "\0\365\0\u0118\0\u013b\0\u015e\0\u0181\0\u01a4\0\u01c7\0\u01ea"+
    "\0\u020d\0\u0230\0\u0253\0\u0276\0\u0299\0\u02bc\0\u02df\0\u0302"+
    "\0\u0325\0\u0348\0\u036b\0\u038e\0\u03b1\0\u03d4\0\u03f7\0\u041a"+
    "\0\u043d\0\u01ea\0\u0460\0\u0483\0\u04a6\0\u04c9\0\u04ec\0\u050f"+
    "\0\u0532\0\u0555\0\u0578\0\u059b\0\u05be\0\u05e1\0\u0604\0\u0627"+
    "\0\u064a\0\u066d\0\u0690\0\u06b3\0\u06d6\0\u06f9\0\u071c\0\u073f"+
    "\0\u0762\0\u0785\0\u07a8\0\u07cb\0\322\0\u07ee\0\u0811\0\u0834"+
    "\0\u0857\0\u087a\0\u089d\0\u08c0\0\322\0\43\0\u08e3\0\u0906"+
    "\0\u0929\0\u094c\0\u096f\0\u0992\0\u09b5\0\322\0\322\0\43"+
    "\0\u09d8\0\u09fb\0\u0a1e\0\u0a41\0\u0a64\0\u0a87\0\u0aaa\0\u0acd"+
    "\0\u0af0\0\u0b13\0\322\0\u0b36\0\u0b59\0\u0b7c\0\322\0\43"+
    "\0\u0b9f\0\u0bc2\0\u0be5\0\u0c08\0\u0c2b\0\322\0\u0c4e\0\u0c71"+
    "\0\322\0\43\0\322\0\u0c94\0\u0cb7\0\u0cda\0\u0cfd\0\u0d20"+
    "\0\u0d43\0\u0d66\0\u0d89\0\u0dac\0\u0dcf\0\u0df2\0\u0e15\0\u0e38"+
    "\0\u0e5b\0\322\0\43\0\322\0\u0e7e\0\43\0\u0ea1\0\u0ec4"+
    "\0\322\0\u0ee7\0\u0f0a\0\u0f2d\0\u0f50\0\322\0\43\0\322"+
    "\0\322\0\43\0\u0f73\0\322\0\43\0\u0f96\0\u0fb9\0\u0fdc"+
    "\0\u0fff\0\322\0\u1022\0\u1045\0\u1068\0\u108b\0\43";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[159];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\2\1\13\1\14\1\15\1\16\1\17\3\20"+
    "\1\21\3\20\1\22\1\20\1\23\1\24\1\25\1\26"+
    "\3\20\1\27\1\20\2\2\54\0\1\30\1\0\1\14"+
    "\42\0\14\20\1\31\1\32\7\20\1\33\15\0\13\20"+
    "\1\34\12\20\15\0\5\20\1\35\3\20\1\36\11\20"+
    "\1\37\2\20\1\40\14\0\26\20\15\0\20\20\1\41"+
    "\5\20\15\0\11\20\1\42\14\20\1\43\14\0\1\20"+
    "\1\44\24\20\15\0\2\20\1\45\23\20\15\0\16\20"+
    "\1\46\7\20\15\0\5\20\1\47\10\20\1\50\7\20"+
    "\15\0\5\20\1\51\20\20\15\0\1\52\42\0\1\20"+
    "\1\53\24\20\15\0\11\20\1\54\14\20\1\55\14\0"+
    "\23\20\1\56\2\20\15\0\1\20\1\57\24\20\15\0"+
    "\13\20\1\60\12\20\15\0\20\20\1\61\5\20\15\0"+
    "\1\20\1\62\16\20\1\63\5\20\35\0\1\64\22\0"+
    "\1\20\1\65\7\20\1\66\14\20\1\67\14\0\15\20"+
    "\1\70\10\20\32\0\1\71\25\0\20\20\1\72\5\20"+
    "\15\0\12\20\1\73\13\20\15\0\13\20\1\74\12\20"+
    "\15\0\3\20\1\75\22\20\15\0\12\20\1\76\6\20"+
    "\1\77\4\20\1\0\1\100\13\0\20\20\1\101\5\20"+
    "\15\0\20\20\1\102\5\20\15\0\14\20\1\103\11\20"+
    "\31\0\1\104\26\0\13\20\1\105\12\20\15\0\15\20"+
    "\1\106\10\20\15\0\5\20\1\107\20\20\15\0\3\20"+
    "\1\110\22\20\15\0\4\20\1\111\21\20\15\0\24\20"+
    "\1\112\1\20\20\0\1\113\37\0\6\20\1\114\17\20"+
    "\15\0\21\20\1\115\4\20\1\0\1\116\34\0\1\116"+
    "\5\0\1\116\13\0\5\20\1\117\20\20\22\0\1\120"+
    "\35\0\1\20\1\121\24\20\15\0\5\20\1\122\20\20"+
    "\15\0\11\20\1\123\14\20\1\124\14\0\22\20\1\125"+
    "\3\20\15\0\16\20\1\126\7\20\15\0\1\20\1\127"+
    "\24\20\16\0\1\130\41\0\4\20\1\131\21\20\15\0"+
    "\11\20\1\132\14\20\1\133\14\0\1\20\1\134\24\20"+
    "\16\0\1\135\41\0\3\20\1\136\22\20\15\0\21\20"+
    "\1\137\4\20\1\0\1\140\13\0\23\20\1\141\2\20"+
    "\15\0\20\20\1\142\5\20\15\0\1\20\1\143\24\20"+
    "\40\0\1\144\17\0\11\20\1\145\14\20\1\146\14\0"+
    "\1\20\1\147\24\20\16\0\1\150\41\0\15\20\1\151"+
    "\10\20\15\0\22\20\1\152\3\20\15\0\7\20\1\153"+
    "\16\20\24\0\1\154\33\0\1\20\1\155\24\20\15\0"+
    "\5\20\1\156\20\20\15\0\13\20\1\157\12\20\30\0"+
    "\1\160\27\0\20\20\1\161\5\20\35\0\1\162\22\0"+
    "\16\20\1\163\7\20\15\0\22\20\1\164\3\20\37\0"+
    "\1\165\20\0\13\20\1\166\12\20\15\0\1\20\1\167"+
    "\24\20\30\0\1\170\27\0\3\20\1\171\22\20\20\0"+
    "\1\172\37\0\12\20\1\173\13\20\15\0\16\20\1\174"+
    "\7\20\15\0\16\20\1\175\7\20\33\0\1\176\24\0"+
    "\15\20\1\177\10\20\15\0\13\20\1\200\12\20\30\0"+
    "\1\201\27\0\5\20\1\202\20\20\22\0\1\203\35\0"+
    "\16\20\1\204\7\20\15\0\4\20\1\205\21\20\33\0"+
    "\1\206\24\0\1\20\1\207\24\20\16\0\1\210\41\0"+
    "\1\20\1\211\24\20\4\0\1\212\10\0\26\20\15\0"+
    "\15\20\1\213\10\20\32\0\1\214\25\0\7\20\1\215"+
    "\16\20\15\0\16\20\1\216\7\20\33\0\1\217\24\0"+
    "\16\20\1\220\7\20\15\0\20\20\1\221\5\20\35\0"+
    "\1\222\23\0\1\223\41\0\16\20\1\224\7\20\33\0"+
    "\1\225\24\0\23\20\1\226\2\20\32\0\1\227\25\0"+
    "\13\20\1\230\12\20\37\0\1\231\20\0\16\20\1\232"+
    "\7\20\22\0\1\233\55\0\1\234\33\0\1\235\14\0"+
    "\1\235\32\0\1\236\44\0\1\237\7\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[4270];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\12\11\14\1\1\0\7\1\1\0\2\1\1\0"+
    "\11\1\1\0\6\1\1\0\2\1\1\0\1\1\1\0"+
    "\6\1\1\0\3\1\1\0\6\1\1\0\2\1\1\11"+
    "\1\1\1\0\3\1\1\0\3\1\1\11\2\1\1\0"+
    "\1\1\1\0\2\1\1\0\3\1\1\0\1\1\1\0"+
    "\1\1\1\11\3\1\1\0\3\1\1\0\1\1\1\11"+
    "\2\1\1\0\2\1\1\0\1\1\1\0\3\1\1\0"+
    "\2\1\1\0\1\1\1\11\2\1\1\11\1\1\1\0"+
    "\1\1\1\0\1\1\1\0\2\1\1\11\2\1\1\11"+
    "\1\0\1\1\1\11\1\1\1\0\1\1\1\0\1\1"+
    "\4\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[159];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */

    StringBuffer string = new StringBuffer();

    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }

    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
      yyline = 1; 
    yychar = 1; 
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { // Agregar el error léxico a la lista
            PanelReporte.agregarError(new Errores("Léxico", yytext() ,"Caracter inválido: " + yytext(), yyline, (int)yychar));
            }
          // fall through
          case 31: break;
          case 2:
            { yyline++; return new Symbol(sym.NEWLINE, yyline, (int)yychar, yytext());
            }
          // fall through
          case 32: break;
          case 3:
            { yychar+=1; /* ignore */
            }
          // fall through
          case 33: break;
          case 4:
            { yychar+=1; return new Symbol(sym.LPAREN,yyline, (int)yychar,yytext());
            }
          // fall through
          case 34: break;
          case 5:
            { yychar+=1; return new Symbol(sym.RPAREN,yyline, (int)yychar, yytext());
            }
          // fall through
          case 35: break;
          case 6:
            { yychar+=1; return new Symbol(sym.TIMES, yyline, (int)yychar,yytext());
            }
          // fall through
          case 36: break;
          case 7:
            { yychar+=1; return new Symbol(sym.PLUS, yyline, (int)yychar,yytext());
            }
          // fall through
          case 37: break;
          case 8:
            { yychar+=1; return new Symbol(sym.COMA,yyline, (int)yychar, yytext());
            }
          // fall through
          case 38: break;
          case 9:
            { yychar+=1; return new Symbol(sym.MINUS,yyline, (int)yychar, yytext());
            }
          // fall through
          case 39: break;
          case 10:
            { yychar+=1; return new Symbol(sym.DIVIDE, yyline, (int)yychar,yytext());
            }
          // fall through
          case 40: break;
          case 11:
            { return new Symbol(sym.NUMERO,  Double.valueOf(yytext()));
            }
          // fall through
          case 41: break;
          case 12:
            { return new Symbol(sym.NOMBRE,yyline, (int)yychar, yytext());
            }
          // fall through
          case 42: break;
          case 13:
            { yychar+=4; return new Symbol(sym.AZUL,yyline, (int)yychar, yytext());
            }
          // fall through
          case 43: break;
          case 14:
            { yychar+=4 ; return new Symbol(sym.GRIS,yyline, (int)yychar, yytext());
            }
          // fall through
          case 44: break;
          case 15:
            { yychar+= 4; return new Symbol(sym.ROJO,yyline, (int)yychar, yytext());
            }
          // fall through
          case 45: break;
          case 16:
            { yychar+= 4; return new Symbol(sym.ROSA,yyline, (int)yychar, yytext());
            }
          // fall through
          case 46: break;
          case 17:
            { yychar+= 5;return new Symbol(sym.CURVA, yyline, (int)yychar, yytext());
            }
          // fall through
          case 47: break;
          case 18:
            { yychar+=5; return new Symbol(sym.LINEA,yyline, (int)yychar, yytext());
            }
          // fall through
          case 48: break;
          case 19:
            { yychar+=5 ; return new Symbol(sym.VERDE,yyline, (int)yychar, yytext());
            }
          // fall through
          case 49: break;
          case 20:
            { yychar+=6; return new Symbol(sym.ANIMAR,yyline, (int)yychar, yytext());
            }
          // fall through
          case 50: break;
          case 21:
            { yychar+=1;return new Symbol(sym.BLANCO,yyline, (int)yychar, yytext());
            }
          // fall through
          case 51: break;
          case 22:
            { yychar+=7;return new Symbol(sym.CELESTE, yyline, (int)yychar,yytext());
            }
          // fall through
          case 52: break;
          case 23:
            { yychar+=7;return new Symbol(sym.CIRCULO, yyline, (int)yychar, yytext());
            }
          // fall through
          case 53: break;
          case 24:
            { yychar+=7 ;return new Symbol(sym.NARANJA,yyline, (int)yychar, yytext());
            }
          // fall through
          case 54: break;
          case 25:
            { yychar+=8 ; return new Symbol(sym.AMARILLO, yyline, (int)yychar, yytext());
            }
          // fall through
          case 55: break;
          case 26:
            { yychar+=8;return new Symbol(sym.CUADRADO,yyline, (int)yychar, yytext());
            }
          // fall through
          case 56: break;
          case 27:
            { yychar+=8; return new Symbol(sym.GRAFICAR, yyline, (int)yychar, yytext());
            }
          // fall through
          case 57: break;
          case 28:
            { yychar+=8;return new Symbol(sym.POLIGONO, yyline, (int)yychar,yytext());
            }
          // fall through
          case 58: break;
          case 29:
            { yychar+=10;return new Symbol(sym.RECTANGULO,yyline, (int)yychar, yytext());
            }
          // fall through
          case 59: break;
          case 30:
            { yychar+=15; return new Symbol(sym.OBJETO_ANTERIOR,yyline, (int)yychar, yytext());
            }
          // fall through
          case 60: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
